eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost

#SPRING
spring:
  application:
    name: Servicio-Principal-Local
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MYSQL5Dialect
    
#SECURITY

server:
  port: 1110
  context-path: /etsidi
#   session:
#     cookie:
#       name: UISESSION
# security:
#   basic:
#     enabled: false
#   oauth2:
#     client:
#       clientId: ClientId
#       clientSecret: secret
#       accessTokenUri: http://localhost:8081/auth/oauth/token
# #       accessTokenUri: http://192.168.1.133:8081/auth/oauth/token
#       userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
# #       userAuthorizationUri: http://192.168.1.133:8081/auth/oauth/authorize
#     resource:
#       userInfoUri: http://localhost:8081/auth/principal
# #       userInfoUri: http://192.168.1.133:8081/auth/principal
