eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


#PORT
server:
  port: 1111

#SPRING
spring:
  application:
    name: Servicio-Principal
